### ISSUE TITLE
OS Command Injection in execa (execa@^1.0.0)

### ISSUE THREAD

**Issue by dylanbutler** [sindresorhus/os-name#11]
dependency execa@^1.0.0 has the following vulnerability reported:

**Description:**
Attackers could trick execa into executing arbitrary binaries. This behaviour is caused by the setting preferLocal=true which makes execa search for locally installed binaries and executes them.

**Identifiers**
windows-release@3.3.3

**Severity**
Critical

Would you mind please updating this lib to pull in your latest `windows-release` so that `execa` may be patched by downstream consumers? Thank you!

**Comment by sindresorhus** [comment]
Please link to the vulnerability report.

**Comment by dylanbutler** [comment]
This was flagged on an internal gitlab server, so I cannot link to it, but here is more context: https://github.com/covidwatchorg/portal/issues/358
