### ISSUE TITLE
Support for commonjs

### ISSUE THREAD

**Issue by amkhapare** [sindresorhus/os-name#14]
Hi,

I currently use version 4.0.0 of os-name and was trying to update os-name 5.0.0 to get the new windows 11 display name and I noticed the below error.

`
    ../../../node_modules/os-name/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import os from 'node:os';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import * as os from 'os';
    > 2 | const osName  = require('os-name');
`

The newer version of os-name (5.0.0) has adopted ES modules and my current project setup doesn't support it.

Is there a way to support commonjs modules?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
