### ISSUE TITLE
why a cli option parser?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/os-name#2]
Unless you're planning on adding a lot of new features, I think that it just bloats the library.

And, of course, thanks for the library.

**Comment by sindresorhus** [comment]
Doesn't really matter. A lot of other modules are using `minimist` and npm 3.0 will deduplicate by default, meaning you'll only have one of it anyways. Dependencies are cheap with npm.

**Comment by stevenvachon** [comment]
Sure, they're cheap, but fewer dependencies is better :) Makes for a faster install. Things can always be improved too.

Thank you for fixing this!

**Comment by sindresorhus** [comment]
> Sure, they're cheap, but fewer dependencies is better :) Makes for a faster install.

Not for long. When npm dedupes by default you'll already have it in the cache and there will be no difference.

**Comment by stevenvachon** [comment]
Dedupe does not remove steps; it only adds them. File size and app runtime memory usage is the only thing that will decrease. If the lib was never even there, npm has one less thing to download+extract+dedupe.

**Comment by sindresorhus** [comment]
Nope. You're forgetting the cache. Yes, dedupe adds some overhead, but with SSD that's not much.

**Comment by stevenvachon** [comment]
If only one dependency depends on minimist, and it happens to be a version that's not yet in cache, it will be downloaded.

Again, it's a perfection thing. Kinda like `files` in package.json
