### ISSUE TITLE
osx version?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/os-name#3]
Instead of "OS X Yosemite", how about "OS X Yosemite 10.10.2"?

**Comment by sindresorhus** [comment]
No. Read the repo name.

If you need that you can use the OS X node module dependency directly.

**Comment by stevenvachon** [comment]
Why then does this library gives the Linux version?

**Comment by sindresorhus** [comment]
Because that's the Linux release name. It doesn't really have a real name. And it's too slow and difficult to get the distribution name. Also explained in the readme.

**Comment by stevenvachon** [comment]
But it still *has* the version in the "name", which was your argument against doing so (at least optionally) for OS X.
